[package]
name = "rinit-service"
version = "0.1.0"
authors = ["Danilo Spinella <oss@danyspin97.org>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
figment = { version = "0.10.19", features = ["toml", "env"] }
indexmap = { version = "2.7.1", features = [ "serde" ] }
libc = "0.2.170"
serde = { version = "1.0.218", features = ["derive"] }
serde_with = "3.12.0"
snafu = "0.8.5"
toml = "0.9.8"
xdg = "3.0.0"
