[package]
name = "rinit-ctl"
version = "0.1.0"
authors = ["Danilo Spinella <oss@danyspin97.org>"]
edition = "2021"

[dependencies]
rinit-ipc= { path = "../ipc" }
rinit-parser = { path = "../parser" }
rinit-service = { path = "../service" }
anyhow = "1.0.96"
clap = { version = "4.5.31", features = ["derive"] }
itertools = "0.14.0"
futures = "0.3.31"
libc = "0.2.170"
serde_json = "1.0.139"
tokio = "1.48.0"

[[bin]]
name = "rctl"
path = "src/main.rs"
